### ISSUE TITLE
بعد از اتمام تحصیل

### ISSUE THREAD

**Issue by Ahmadreza-SY** [ssheikholeslami/EIT-Digital-In-Farsi#10]
با سلام و تشکر فراوان بابت اطلاعات کاملتون

خواستم بدونم آیا بعد اتمام تحصیل موظف به برگشت به ایران هستیم؟
چون یکی از شروط بعضی اسکلارشیپ‌های اروپا اینه که حداقل دو سال بعد تحصیل در وطنت باشی

**Comment by ssheikholeslami** [comment]
سلام. نه، این اسکالرشیپ هیچ تعهدی برای شما نمیاره. نه از طرف ایران نه از طرف اروپا. تنها قیدی که داره اینه که در مدتی که این اسکالرشیپ رو دارین، نمیتونین اسکالرشیپ دیگه‌ای که پولش از طرف اتحادیه‌ی اروپا تأمین میشه رو هم بگیرین.
ضمن اینکه هدف کلی این برنامه اینه که دانشجوها از کشورهای مختلف بیان و توی اروپا بمونن و به توسعه‌ی فناوری تو اروپا کمک کنن.

**Comment by Ahmadreza-SY** [comment]
خیلی هم عالی
ممنون بابت راهنمایی و وقتتون
