### ISSUE TITLE
هزینه‌ی خوابگاه یا محل زندگی

### ISSUE THREAD

**Issue by MohGanji** [ssheikholeslami/EIT-Digital-In-Farsi#11]
شما در مورد هزینه‌ ها یه توضیحی دادید، ولی یذره شفاف تر می‌خواستم بپرسم که الان هزینه‌هایی که گفتید مربوط به شهریه دانشگاه می‌شد همش و اینطوری بود که برای نصفه‌ی دیگه‌ی هزینه‌ی شهریه باید کار کنیم.
هزینه‌ی محل زندگی و کلا هزینه‌های روزمره‌ی زندگی رو در موردشون حرفی نزدید.

با توصیفات شما حس کردم لازمه که یه مقدار خوبی خودمون هزینه کنیم برای این پروگرم. اگه می‌شه بیشتر قسمت مربوط به هزینه‌ها رو شفاف کنین

**Comment by ssheikholeslami** [comment]
بسته به ۱) میزان اسکالرشیپی که میگیرین و ۲) شهری که توش هستین ممکنه لازم شه یا نشه که خودتون هزینه کنین. شهرهای اروپای غربی و شمال غرب معمولن گرونتر هستن و بین سیصد و پنجاه تا مثلن ششصد یورو در ماه باید برای اجاره درنظر بگیرین. خورد و خوراک هم باز تو جاهای مختلف فرق داره. میشه گفت مثلن هزینه‌ی زندگی (اجاره، غذا، ...) ماهانه تو آیندهوون و استکهلم بین پونصد تا هشتصد یوروئه.

**Comment by ssheikholeslami** [comment]
نکته‌ی دیگه اینکه توی خیلی از این کشورها شما اجازه‌ی کار پاره‌وقت دارین و خیلیا تمام هزینه‌ها رو با این کار پوشش میدن. اکثر این کارهای پاره‌وقت هم کاملن مرتبط با رشته‌ی بچه‌ها هستن. ینی مثلن کارآموزی دیتاساینس یا مهندسی نرم‌افزار و ... میرن یا به عنوان مهندس یا توسعه‌دهنده‌ی پاره‌وقت کار میکنن. توی بعضی دانشگاه‌ها هم میشه تی‌ای شد و پول خوبی درآورد. من شهریه‌ی یک ترم از چهار ترمم رو فقط با یه دونه تی‌ای شدن دادم.
