### ISSUE TITLE
حجم درس

### ISSUE THREAD

**Issue by MohGanji** [ssheikholeslami/EIT-Digital-In-Farsi#12]
تو این پروگرم شما توضیح دادین که درطول دو سال باید ۱۲۰ واحد پاس کنیم، حالا کورس‌هاشون رو دیدم و اکثرا ۵ یا ۶ واحدین، ولی بازم با این شرایط یعنی حدود ۶۰ واحد ارشد خودمون باید توی دو سال کورس پاس کنیم، این مقدار حجمش رو می‌شه هندل کرد در حالی که کنارش قراره کار هم بکنیم؟

**Comment by ssheikholeslami** [comment]
شما «قرار نیست» کار هم بکنین ولی خیلی از بچه‌ها در کنار درسشون کار هم میکنن و مشکلی پیش نمیاره. این عددش یه مقدار ممکنه ترسناک به نظر برسه ولی حجم کار شبیه مثلن دو سال لیسانسه. مسئله اینه که برنامه‌ و سرفصل‌های درس‌ها و تمرینا و امتحان و ... مشخصه و آدم خیلی راحت میتونه برنامه‌ریزی کنه و مطمئن باشه که اگه مثلن فلان کار و فلان کار رو بکنه میتونه هم درس رو خیلی خوب یاد بگیره هم نمره‌ی خیلی خوبی بگیره. به استثنای چند درس معدود، بقیه‌ی درس‌ها اصلن پرفشار نیستن.

**Comment by MohGanji** [comment]
خب اگه بخوایم هزینه‌هاش رو هم کاور کنیم تقریبا کار بخش جدانشدنی این پروگرم می شه.
من دوران کارشناسیم هم کار کردم، ولی خب با حجم کار پاره وقت اروپا و کنارش حجم درس خیلی آشنا نیستم هنوز.

ولی اگه اینطور که شما می‌گین کسانی هستن که این کار رو کردن پس شدنیه.
مرسی.
