### ISSUE TITLE
نمره زبان

### ISSUE THREAD

**Issue by aliasgharkhani** [ssheikholeslami/EIT-Digital-In-Farsi#15]
سلام
ببخشید اگه نمره زبانمون(نمره کل) از نمره کل اونا بیشتر باشه ولی تو یکی از بخش ها یه نمره کمتر باشیم و از طرف دیگه دانشگاهی رو بخوایم انتخاب کنیم که حداقل نمره زبانشون به ما میخوره، بازم گیر میدن؟
یا نه همین که با حداقل دانشگاه اکی باشیم حله
ممنون

**Comment by hsnfirooz** [comment]
سلام.
معمولا وقتی حد نصابی روی نمره زبان هست، فرقی نمیکنه این حد نصاب روی کل نمره باشه یا روی یه بخش خاص و بسیار جدی گرفته میشه و اگه نمره لازم رو نداشته باشین، ریجکت میشین.
حداقل نمره‌ای از طرف EIT وجود نداره و شما فقط باید حد نصاب دانشگاه‌هایی که میخواین برین رو داشته باشین.
جزئیات نمرات هر دانشگاه اینجا مشخصه: [لینک](https://masterschool.eitdigital.eu/application/admissions-criteria)
