### ISSUE TITLE
scholarship criteria

### ISSUE THREAD

**Issue by ghost** [ssheikholeslami/EIT-Digital-In-Farsi#16]
سلام سینا جان، خوبی؟
من همین الان پستی که در مورد EIT نوشتی رو خوندم، کلی ذوق کردم که یکی در موردش نوشته. از بخت خوبم ددلاین رو رد نکردم، چک کردم دیدم امروز 3 فوریه آخرین روز ددلاینه. :دی
من هم زمان با دو سال آخر کارشناسی سر کار می رفتم و با اینکه الان تو دو تا فیلم autonomous systems و embedded systems رزومه ی کاری و ریسرچی خوبی دارم معدلم سر اون دو سال رسیده به 14. معدل برای این پروگرم مثل بقیه جاها حرف اول رو میزنه برای اسکولارشیپ گرفتن؟ رشته ها و دانشگاهای این پروگرم دقیقا همون چیزیه که من میخوام، ولی اگه نتونم اسکولارشیپ بگیرم با وضعیت ارز باید بی خیالش بشم.

**Comment by ssheikholeslami** [comment]
سلام، ببخشید من الان دیدم ایشوی شما رو. اینجا معدل حرف اول رو نمیزنه و بیشتر براشون پتانسیل نوآوری و این داستان‌ها مهمه. من خودم معدلم ۱۳.۷۳ بود :دی ولی خب سال اولی که اپلای کردم ادمیشن بدون اسکالرشیپ گرفتم، سال دوم که اپلای کردم چون سر کار میرفتم و کارم مرتبط بود تونستم اسکالرشیپ هم بگیرم و دیگه همون رو رفتم. یعنی فکر میکنم سابقه‌ی کاری خیلی تأثیر داشت چون تنها فرقی که اپلیکیشن من تو اون یه سال کرده بود همون بود.
اگه میخوای اپلای کنی به نظرم در مورد اون ایده‌ی بیزینسی که باید بنویسی وقت خوبی بذار (پیشنهاد من اینه که یه خرده در مورد 
Business Model Canvas
بخون و سعی کن در قالب اون تحلیل کنی ایده‌ت رو. مهم نیست ایده چقدر جدید و اینا باشه، مهم اینه که نحوه‌ی فکر کردنت رو نشونشون بدی. این چهارچوب خیلی کمک میکنه و یه‌جورایی از کامپوننت‌های اصلی درس‌های مربوط به بیزینسِ این پروگرم حساب میشه).
والا تا امسال که اپلیکیشن فی نمیگیرفتن من همه رو تشویق میکردم که حتمن اپلای کنن، ولی خب الان اپلیکیشن فی هم اضافه شده، تصمیم یه خرده سخته.
امیدوارم موفق باشی!

**Comment by ghost** [comment]
خوب من یه آپدیت بدم که چی شد. :دی
من دیروز عصر از سر کار اومدم نشستم اپلیکیشن رو پر کنم دیدم اصلا چنین جایی تو پرتال وجود نداره. کل سایت رو زیر و رو کردم دیدم همه جا نوشتن 3 فوریه. ایمیل زدم امروز جواب دادن ما ساعت 17 فرم رو قفل کردیم. و هیچ جا اشاره نکردن به چنین ساعتی! :|
حالا اون کال دوم هست هنوز ولی احتمالا فقط برای کشورهای اتحادیه اروپا باشه.

**Comment by ssheikholeslami** [comment]
ئه، حیف. آره اون کال دوم احتمال اسکالرشیپ گرفتن خیلی کمتره. فکر نمیکنم بیارزه به این ترتیب.
