### ISSUE TITLE
مدرک

### ISSUE THREAD

**Issue by hadisinaee** [ssheikholeslami/EIT-Digital-In-Farsi#2]
سلام،
خیلی ممنون بابت توضیحات مفصل و کاملتون. من بخش مدرک رو سوال داشتم. من مدرک اصلی رو باید پول بدم و بگیرم. آیا میشه با ریز نمرات غیر رسمی و گواهی موقت اقدام کرد؟

**Comment by ssheikholeslami** [comment]
سلام، ممنونم. بله، شما با ریزنمرات و گواهی موقت اپلای میکنید (فکر میکنم میتونید در حین دانشجو بودن هم ریزنمرات انگلیسی بگیرید) و با اون‌ها اپلای کنید. به شما پذیرش مشروط میدن و موقع ثبت نام باید اصل مدرک و ترجمه‌ی اون رو به دانشگاه سال اولتون تحویل بدید.
