### ISSUE TITLE
تمکن مالی بعد از گرفتن اسکولارشیپ

### ISSUE THREAD

**Issue by hadisinaee** [ssheikholeslami/EIT-Digital-In-Farsi#3]
یک سوال کمی غیرمرتبط هست داشتم از خدمتتون.
آیا لازمه که مدارک مبنی بر تمکن مالی رو به سفارت سوئد ارائه کنیم اگر موفق شده باشیم اسکولارشیپ بگیریم؟ اگر لازمه حدودا چه مقداری هست؟

ممنونم

**Comment by ssheikholeslami** [comment]
اگر اسکالرشیپ رو دریافت کنید به اندازه‌ی میزان یک سال اسکالرشیپتون از اون مبلغ کم میشه. مثلن در مورد سوئد اینطوری هست که باید نشون بدید به ازای هر ماه دوران تحصیلتون (در اینجا میشه مثلن دوازده ماه) ۸۱۹۰ کرون دارید (چیزی نزدیک ۸۱۰ یورو مثلن) که برای یک سال درمیاد حدود ده هزار یورو.

حالا اگر اسکالرشیپی رو بگیرید که پونصد یورو در ماهه، شش هزار یورو از اون کم میشه به خاطر اسکالرشیپ (و گواهیش رو آپلود میکنید) و باقی مبلغ باید توی حساب بانکیتون باشه. من سوئد سال دومم بود و یه گزارش حساب از حسابی که دانشگاه آیندهوون توی هلند برام باز کرده بود براشون فرستادم، صرفن لازم بود که به انگلیسی باشه.
برای هلند هم رقمش همین حوالی بود و همین اسکالرشیپ جزوش حساب میشد. تا جایی که میدونم برای تمام این کشورها اینطوریه. منتها برای هلند، دانشگاه خودش برای من یک حساب باز کرده بود و باید پول رو به اون حساب میریختم.
