### ISSUE TITLE
رتبه ی دانشگاه ها و انگیزه نامه

### ISSUE THREAD

**Issue by niloo-sh** [ssheikholeslami/EIT-Digital-In-Farsi#4]
با تشکر از متن کامل و خوبتون فقط من دوتا سوال داشتم
1. امکانش هست رتبه ی دانشگاه های فعال در دیتاساینس رو بگید که به چه صورت مثلا ایندهوون،کی تی اچ و دانشگاه برلین و فنلاند و دانمارک
2. اینکه باید در انگیزه نامه یک ایده ی تجاری داشته باشیم. باید درچه حد باشه و چه جنبه هاییش رو باید در نظر بگیریم
ممنونم از وقتی که میذارید.

**Comment by ssheikholeslami** [comment]
سلام. در مورد رتبه‌بندی‌ها خب توی ویکیپدیای هر دانشگاه رو اگه ببینین میتونین پیداش کنین. این دانشگاه‌ها جزو دانشگاه‌های معروف مهندسی در دنیا هستن. مثلن توی یکی از رتبه‌بندی‌ها فک کنم دانشگاه آیندهوون توی مهندسی ۳۷ دنیا بود. ولی خب اینا خیلی مهم نیست. مهم ارتباط اون دانشگاه‌ها با مراکز تحقیقاتی دیگه و شرکت‌هاست. از این لحاظ همه‌ی این دانشگاه‌ها جزو تاپ‌های دنیا هستند.
گروه دیتابیس تی‌یو برلین توی دنیا خیلی معروفه البته. آیندهوون هم توی دیتاساینس معروفه و تا پارسال یه آقایی به اسم ویل فن‌درآلست عضو هیئت علمی اونجا بود (و ما باهاش درس داشتیم کوارتر اول) که پایه‌گذار یه شاخه به اسم پراسس ماینینگه و جزو ده پونزده تا استاد پراستناد دنیا تو علوم کامپیوتره (البته امسال دیگه رفت دانشگاه آخن). دانشگاه کی‌تی‌اچ هم که خب توی زمینه‌ی ما، گروه دیستریبیوتد سیستمزش توی دنیا مطرحه. خلاصه منظورم اینه که این دانشگاه‌ها از لحاظ اعتبار و کیفیت واقعن ممتاز هستند و دیگه کار به مقایسه‌ی رتبه‌بندی نمیرسه.
البته تا جایی که خبر دارم دانشگاه‌های دانمارک هنوز عضو این برنامه نیستن.

**Comment by ssheikholeslami** [comment]
در مورد سئوال دومتون فکر میکنم توی متن توضیحات کافی دادم. ولی در مورد خودم اینطوری بود که صرفن دو سه پاراگراف در مورد ایده نوشتم و سعی کردم برای یک سرمایه‌گذار احتمالی توضیحش بدم و قانعش کنم. اون موقع با این فرمت آشنا نبودم. احتمالن بد نباشه یه چیزی تو مایه‌های 
executive summary
بنویسید. اگر این رو سرچ کنید (به همراه همون
business model canvas)
ساختار خیلی خوبی پیدا خواهد کرد متنتون. 
چیزهایی که معمولن مهم هست اینه که نشون بدین دارین یک مسئله‌ی مشخص و نیاز رو رفع میکنین (و اون مسئله رو واضح توضیح بدین)، شناخت نسبی از بازار محصولتون دارین، برای مارکتینگش ایده دارین، و رقبای احتمالی رو میشناسین و احیانن یک نقشه‌ی راه یکی دو ساله هم مدنظرتون هست. ولی خب یه بخش مهمی از این برنامه اینه که بچه‌ها این موارد رو یاد بگیرن :) پس خیلی سخت نگیرید. ولی خب هرچقدر ایده رو بهتر و واضح‌تر توضیح بدین طبیعتن بهتره.
