### ISSUE TITLE
درباره انتخاب دانشگاه ها 

### ISSUE THREAD

**Issue by SajjadRashidiani** [ssheikholeslami/EIT-Digital-In-Farsi#5]
سلام 
خیلی خیلی خسته نباشید و دمتون گرم که این راهنمای جامع و کامل رو نوشتید. 
من برای یکی دوتا از دانشگاه های سال اول یکی از پروگرام ها (برای رشته برق) جدا گانه اپلای کردم به نظرتون مشکل ساز میشه اگر از طریق این برنامه هم اپلای کنم؟ 
خیلی ممنون میشم اگر راهنمایی کنید

**Comment by kargaranamir** [comment]
سلام ممنون میشم اگه جواب بدید 
من نیز همین سوال را دارم

**Comment by ssheikholeslami** [comment]
سلام. والا این از اون سئوال‌هاییه که فقط خود ادمیشن کامیتی میتونه بهشون جواب بده 😄 ادمیشن کامیتی‌های دانشگاه‌هایی که براشون اپلای میکنید پرونده‌ی شما رو بررسی میکنند و اون‌ها هستن که پذیرش نهایی رو به شما میدن. شاید این مورد براتون راهگشا باشه.

**Comment by SajjadRashidiani** [comment]
خیلی ممنون از پاسختون.
