### ISSUE TITLE
unofficial transcript issue

### ISSUE THREAD

**Issue by alihares99** [ssheikholeslami/EIT-Digital-In-Farsi#6]
سلام
ممنون از توضیحات بسیار خوبتون.
من با مسئول EIT مکاتبه کردم
و اینا بهم گیر دادن که چرا بالای کارنامه ات نوشته غیر رسمی
هر چی هم براشون توضیح دادم گفتن که ما مدرک غیر رسمی قبول نمی کنیم
گفتم اگه بخواید براتون توی پاکت مهر و موم شده ی دانشگاه پست می کنم
ولی باز گفتن که نه، مدرک پست شده قبول نمی کنیم.
خلاصه نمی دونم چی کار کنم.
ایده ای دارید؟
من کارنامه کارشناسیم رو از دانشگاه شریف می گیرم.

**Comment by ssheikholeslami** [comment]
سلام. به من یه ایمیل بزن و توش توضیح بده قضیه رو، من ببینم شاید بتونم مکاتبه بکنم باهاشون

**Comment by alihares99** [comment]
من الان براتون ایمیل آخری که از طرف EIT
اومده رو فوروارد می کنم. توی این ایمیل می تونید تاریخچه تمام صحبت هامون رو ببینید.
ظاهرا به هیچ صراطی مستقیم نمیشن

**Comment by parsafarshadfar** [comment]
salam. manam karshenasi e sharif mikhunam o mikham baraye EIT apply konam. mikhastam bedunam baraye in moshkel, che rahe halli hast?

**Comment by kargaranamir** [comment]
سلام این مشکل حل شد؟ 
اگه حل شده میشه راه حلش را بیان کنید؟

**Comment by ssheikholeslami** [comment]
سلام. تا جایی که من میدونم نه، ولی خود بچه‌ها باید بیان تجربه‌شون رو بگن.
