### ISSUE TITLE
نامه‌ی تضمین اتمام درس تا تابستان

### ISSUE THREAD

**Issue by xhebb** [ssheikholeslami/EIT-Digital-In-Farsi#7]
سلام. یکی از نیازمندی‌های این برنامه اینه که اگه هنوز فارغ‌التحصیل نشدیم یک نامه‌ای بدیم که تضمین می‌کنه تا تابستون فارغ‌التحصیل می‌شیم. می‌دونید که چه افرادی می‌تونن این نامه رو بدن و چه میزان رسمی باید باشه؟ چون آموزش که به صورت انگلیسی نمی‌ده چنین نامه‌ای رو. من تو دانشکده‌ی فنی دانشگاه تهران هستم

**Comment by ssheikholeslami** [comment]
سلام. اگه متن رو کامل خونده باشید توی قسمت 
https://github.com/ssheikholeslami/EIT-Digital-In-Farsi#اقدام-برای-گرفتن-پذیرش-یا-همون-اپلای-کردن
توضیح داده‌ام. اگه با این حال باز سئوال داشتین بفرمایید
