### ISSUE TITLE
اسکالرشیپ

### ISSUE THREAD

**Issue by erfangholami** [ssheikholeslami/EIT-Digital-In-Farsi#8]
سلام
خیلی راهنمایی دقیقی بود و ممنون بابتش.
یه چیزی که من پیگیریش کردم اسکالرشیپش بود که برای هر نوعش 50 درصد شهریه دانشگاه مقصد روو در بر میگیره. اما خب هزینه سالانش حدود 12 هزار تاست که با 50 درصد میشه 6 هزار تا.و با قیمت الان یورو توو کشور یه کم سخته جور کردن همچین هزینه ای. و از اونجایی که از بدو ورود شهریه سال روو میگیرن باید حتما قبلش تهیه کرد و با کار کردن اونجا میشه برای سال دوم هزینه ها روو جور کرد. میخواستم بدونم ایا غیر از اون 50 درصد میتونن برای دانشجوهایی مثل ایرانی ها شرایط خاص در نظر بگیرن و مقدارشو تغییر بدن؟

**Comment by ssheikholeslami** [comment]
سلام
شما هر شیش ماه یکبار باید نصف شهریه‌ی یکسال رو پرداخت کنین (ینی سه هزار یورو). اولین باری که باید پرداخت کنید طرفای اردیبهشت-خرداد قبل از رفتنتونه. اواخر سپتامبر هم اولین بسته‌ی شش ماهه‌ی اسکالرشیپ رو به حسابتون واریز میکنن.
با کار کردن و این‌ها میشه تا حدی هزینه‌ها رو پوشش داد، ولی بستگی به این داره که اون کشوری که هستین محدودیت ساعت کاری برای دانشجویان/خارجی‌ها داشته باشه یا نه. مثلن زمان ما توی هلند فقط میشد حداکثر هفته‌ای ده ساعت کار کرد، ولی از پارسال محدودیت رو برداشتن. البته با همون محدودیت هم من و دوستام تونستیم تدریسیار یه درسی بشیم که دوتا کوارتر ادامه داشت و براش نزدیک دو هزار و سیصد یورو گرفتیم، یعنی اندازه‌ی شهریه‌ی یه ترم.
در مورد ایرانی‌ها بعیده استثنای خاصی قائل بشن چون سیاستشون اینه (حضوری چندبار صحبت کردم باهاشون در این مورد) که اگه برای ایران استثنا قائل بشیم باید برای خیلی از کشورهای دیگه هم اینکارو کنیم. و گفته بودن که چون وضع ارتباط سیاسی ایران با اتحادیه‌ی اروپا خیلی هم خوب نیست، یک مقداری بعیدتره این موضوع. ولی کاری که ممکنه بکنن اینه که مثلن سعی کنن اسکالرشیپی که پول بیشتری میده رو بیشتر به ایرانیا اختصاص بدن. ما و بقیه‌ی بچه‌های ایرانی هر فرصتی که میشه سعی میکنیم این فشار رو بیاریم بهشون، و البته خودشون هم کاملن در جریان هستن ولی چون بودجه‌ی برنامه از اتحادیه اروپا میاد باید یه سری روال سیاسی و قانونی طی بشه که هم زمان‌گیره هم با توجه به شرایط فعلی یک مقداری بعیده

**Comment by erfangholami** [comment]
مرسی از توضیحاتت :))
