### ISSUE TITLE
مدرک کارشناسی

### ISSUE THREAD

**Issue by Satiilee** [ssheikholeslami/EIT-Digital-In-Farsi#9]
سلام.
مرسی از معرفی خوبت. 
شرایطش برای کساییکه مدرک کارشناسیشون یه رشته دیگه است ولی میخوان بیان کامپیوتر چیه؟ من فیزیک خوندم ولی کار کامپیوتر میکنم یکم و دوست دارم. الان دیدم زده رشته مربوط باشه کارشناسی...

**Comment by ssheikholeslami** [comment]
سلام. به هرحال باید یه طوری نشون بدین که یا  درس‌های مرتبط گذروندین یا سابقه‌ی کاری مرتبط دارین. ارتباط هم بسته به رشته فرق میکنه. مثلن برای دیتاساینس باید بتونین نشون بدین که تجربه‌ی برنامه‌نویسی دارین و درس‌های آمار و ... گذروندین یا آشنایی دارین. برای رشته‌های پایه مثل ریاضی و فیزیک، نشون دادن این ارتباط نباید سخت باشه، چون انتظار میره که تسلط خیلی خوبی به ریاضی و مباحث تئوری و آمار و ... داشته باشین. میتونین با گذروندن چندتا کورس آنلاین و انجام دادن پروژه‌های اون‌ها تا حد خوبی این موضوع رو محقق کنین. من پیشنهادم اینه که حداقل یکی یا دوتا از کورس‌های خود ای‌آی‌تی (که توی متن توضیح داده‌ام) رو هم بگذرونین.
